name:                eyepatch
version:             0.1.0.0
github:              "mrak/eyepatch"
license:             BSD3
author:              "Eric Mrak"
maintainer:          "mail@ericmrak.info"
copyright:           "2018 Eric Mrak"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/eyepatch#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- binary
- docopt
- directory
- either

library:
  source-dirs: src

executables:
  eyepatch:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eyepatch

tests:
  eyepatch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eyepatch
